name: node-module-polyfill
version: 1.0.0
description: Polyfills for the Node.Module interface
author: Danielle Church <dani.church@gmail.com>
license: ISC
keywords:
  - node.Module
  - createRequire
  - createRequireFromPath
  - require
  - polyfill

main: dist/index.js
types: dist/index.d.ts
scripts:
  build: tsc
  watch: tsc --watch
  prepare: tsc
  test: jest
  coverage: jest --coverage

jest:
  preset: ts-jest
  testEnvironment: node
  testMatch:
    - <rootDir>/test/init.ts
    - <rootDir>/test/test-*.ts
  testSequencer: <rootDir>/test/sequencer
  collectCoverageFrom:
    - <rootDir>/src/**/*.ts
    - <rootDir>/test/**/*.ts

repository:
  type: git
  url: git+https://github.com/dmchurch/node-module-polyfill.git
bugs:
  url: https://github.com/dmchurch/node-module-polyfill/issues
homepage: https://github.com/dmchurch/node-module-polyfill#readme

dependencies:
  "@types/node": ^12.7.8
  semver: ^6.3.0
devDependencies:
  package-yaml: ^1.0.0
  typescript: ^3.6.3
  "@types/semver": ^6.0.2
  jest: ^24.9.0
  "@types/jest": ^24.0.18
  jest-mock-console: ^1.0.0
  ts-jest: ^24.1.0
